services:
  stock-advisor-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shikanga-stock-advisor-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=shikanga-stock-advisor-user'
    ports:
      - '5432:5432'
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: alexander@shikanga.co.uk
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8081:80'
    depends_on:
      - stock-advisor-postgres
    restart: unless-stopped
