name: Multi-agent Codex workflow

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - "**.py"
      - ".github/workflows/agents-workflow.yml"

jobs:
  run-agents:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Codex CLI
        run: npm i -g @openai/codex

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run multi-agent workflow
        run: python multi_agent_workflow.py
